import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ROUTES } from "../src/data/routes.ts";
import { TERMINALS_BY_ID } from "../src/data/terminals.ts";
import {
  buildMeshGraph,
  meshPathCoordinates,
  type MeshFeatureCollection,
} from "../src/domain/mesh.ts";

const MESH_PATH = resolve("data/salish-mesh.json");
const OUTPUT_PATH = resolve("src/data/route-leg-geometry.ts");

const directedLegKey = (fromId: string, toId: string): string =>
  `${fromId}\0${toId}`;

const compareCodeUnits = (a: string, b: string): number => {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
};

const loadMesh = (): MeshFeatureCollection =>
  JSON.parse(readFileSync(MESH_PATH, "utf8")) as MeshFeatureCollection;

export const buildRouteLegGeometryByDirectedTerminalIds = (): Readonly<
  Record<string, readonly (readonly [number, number])[]>
> => {
  const graph = buildMeshGraph(loadMesh());
  const geometryByDirectedTerminalIds = new Map<
    string,
    readonly (readonly [number, number])[]
  >();

  for (const route of ROUTES) {
    for (let legIndex = 0; legIndex < route.terminalIds.length - 1; legIndex++) {
      const fromId = route.terminalIds[legIndex];
      const toId = route.terminalIds[legIndex + 1];
      if (fromId === undefined || toId === undefined) continue;

      const from = TERMINALS_BY_ID.get(fromId);
      if (from === undefined) {
        throw new Error(`unknown terminal id ${fromId} on route ${route.id}`);
      }

      const to = TERMINALS_BY_ID.get(toId);
      if (to === undefined) {
        throw new Error(`unknown terminal id ${toId} on route ${route.id}`);
      }

      const directedKey = directedLegKey(from.id, to.id);
      if (geometryByDirectedTerminalIds.has(directedKey)) continue;

      const coordinates = meshPathCoordinates(graph, from.coordinates, to.coordinates);
      if (coordinates !== null) {
        geometryByDirectedTerminalIds.set(directedKey, coordinates);
      }
    }
  }

  return Object.fromEntries(
    [...geometryByDirectedTerminalIds.entries()].sort(([leftKey], [rightKey]) =>
      compareCodeUnits(leftKey, rightKey)
    )
  );
};

const renderRouteLegGeometryModule = (
  geometryByDirectedTerminalIds: Readonly<
    Record<string, readonly (readonly [number, number])[]>
  >
): string => {
  const renderedEntries = Object.entries(geometryByDirectedTerminalIds)
    .map(([key, coordinates]) => {
      const renderedCoordinates = coordinates
        .map(
          ([longitude, latitude]) =>
            `    [${longitude}, ${latitude}],`
        )
        .join("\n");
      return `  ${JSON.stringify(key)}: [\n${renderedCoordinates}\n  ],`;
    })
    .join("\n");

  return `export type RouteLegCoordinate = readonly [number, number];

/**
 * Build-time baked mesh geometry keyed by directed terminal pair, as
 * "fromTerminalId\\0toTerminalId".
 *
 * Generated by \`npm run build-route-geometry\` from \`data/salish-mesh.json\`;
 * legs not present here fall back to straight lines. Keeping this in
 * \`src/data\` avoids shipping the ~800 KB mesh to the client bundle.
 */
export const ROUTE_LEG_GEOMETRY_BY_DIRECTED_TERMINAL_IDS: Readonly<Record<string, readonly RouteLegCoordinate[]>> = {
${renderedEntries}
};
`;
};

export const writeRouteLegGeometryModule = (): void => {
  const geometryByDirectedTerminalIds = buildRouteLegGeometryByDirectedTerminalIds();
  writeFileSync(
    OUTPUT_PATH,
    renderRouteLegGeometryModule(geometryByDirectedTerminalIds)
  );
};

if (
  process.argv[1] !== undefined &&
  import.meta.url.startsWith("file:") &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  writeRouteLegGeometryModule();
}
